### ISSUE TITLE
Fix item_spec file tests and ruby versions for each member

### ISSUE THREAD

**Issue by redferret** [redferret/black_thursday#48]
### What:
Tests are failing on `BigDecimal.new`
```sh
1) Item#initialize exists
     Failure/Error: unit_price: BigDecimal.new(10.99,4),
     
     NoMethodError:
       undefined method `new' for BigDecimal:Class
     # ./spec/item_spec.rb:12:in `block (3 levels) in <top (required)>'
.
.
.
```

### Why:
Ruby version on Richard's computer is set to 2.7.2, bundler doesn't work on 2.5.3 even after installing for 2.5.3 but works perfectly find with 2.7.2 or higher.

### .ruby-version
Suggest to add `.ruby-version` file at the root of the project directory and add `2.7.2` to the file to set all environments to this version.

### Steps to fix and to catch up on ruby version

1. Upgrade to ruby version to 2.7.2 by running `rbenv install 2.7.2`
2. Add the `.ruby-version` file as described above with the 2.7.2 version
3. run `bundle` at the root directory of project (This will install all gems for this version)
4. use `BigDecimal()` rather than `BigDecimal.new()` as per the depreciation notes on `BigDecimal`

Effort Points 1
